# Generated by Django 5.1.1 on 2024-09-22 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CbtAuthor',
            fields=[
                ('PR_AUTHOR_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PR_AUTHOR_NAME', models.CharField(max_length=255)),
                ('PR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cbt_author',
            },
        ),
        migrations.CreateModel(
            name='CbtBoard',
            fields=[
                ('PR_BOARD_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PR_BOARD_NAME', models.CharField(max_length=100)),
                ('PR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cbt_board',
            },
        ),
        migrations.CreateModel(
            name='CbtBookType',
            fields=[
                ('PR_IMPRINT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PR_BOOK_NAME', models.CharField(max_length=255)),
                ('PR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cbt_book_type',
            },
        ),
        migrations.CreateModel(
            name='CbtClasses',
            fields=[
                ('PR_CLASS_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PR_CLASS_NAME', models.CharField(max_length=100)),
                ('PR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cbt_classes',
            },
        ),
        migrations.CreateModel(
            name='CbtEdition',
            fields=[
                ('PR_EDITION_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PR_EDITION_NAME', models.CharField(max_length=50)),
                ('PR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cbt_edition',
            },
        ),
        migrations.CreateModel(
            name='CbtImprint',
            fields=[
                ('PR_IMPRINT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PR_IMPRINT_NAME', models.CharField(max_length=255)),
                ('PR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cbt_imprint',
            },
        ),
        migrations.CreateModel(
            name='CbtSeries',
            fields=[
                ('PR_SERIES_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PR_SERIES_NAME', models.CharField(max_length=255)),
                ('PR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
                ('PR_BOARD_NAME', models.ManyToManyField(blank=True, related_name='series', to='websiteApp.cbtboard')),
                ('PR_CLASS_NAME', models.ManyToManyField(blank=True, related_name='series', to='websiteApp.cbtclasses')),
            ],
            options={
                'db_table': 'cbt_series',
            },
        ),
        migrations.CreateModel(
            name='CbtExcelData',
            fields=[
                ('PR_EXCEL_DATA_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PR_TITLE', models.CharField(blank=True, max_length=255, null=True)),
                ('PR_SUB_TITLE', models.CharField(blank=True, max_length=255, null=True)),
                ('PR_ISBN', models.CharField(blank=True, max_length=255, null=True)),
                ('PR_BOOK_TYPE', models.CharField(blank=True, max_length=100, null=True)),
                ('PR_BOOK_NUMBER', models.IntegerField(blank=True, null=True)),
                ('PR_CLASS_LEVEL', models.CharField(blank=True, max_length=100, null=True)),
                ('PR_PRODUCT_DIVISION', models.CharField(blank=True, max_length=100, null=True)),
                ('PR_BROAD_SUBJECT', models.CharField(blank=True, max_length=255, null=True)),
                ('PR_DETAILED_SUBJECT', models.CharField(blank=True, max_length=255, null=True)),
                ('PR_BOOK_CODE', models.CharField(blank=True, max_length=100, null=True)),
                ('PR_COPYRIGHT', models.CharField(blank=True, max_length=50, null=True)),
                ('PR_DATE_OF_RELEASE', models.DateField(blank=True, null=True)),
                ('PR_BINDING', models.CharField(blank=True, max_length=50, null=True)),
                ('PR_LANGUAGE', models.CharField(blank=True, max_length=50, null=True)),
                ('PR_PAGES', models.IntegerField(blank=True, null=True)),
                ('PR_TRIM_SIZE', models.CharField(blank=True, max_length=50, null=True)),
                ('PR_WEIGHT', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('PR_LIST_PRICE', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('PR_DISCOUNT', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('PR_PRODUCT_DESCRIPTION', models.TextField(blank=True, null=True)),
                ('PR_COMPANY', models.CharField(blank=True, max_length=255, null=True)),
                ('PR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
                ('PR_AUTHOR', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='websiteApp.cbtauthor')),
                ('PR_EDITION', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='websiteApp.cbtedition')),
                ('PR_IMPRINT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='websiteApp.cbtimprint')),
                ('PR_SERIES', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='websiteApp.cbtseries')),
            ],
            options={
                'db_table': 'cbt_excel_data',
            },
        ),
    ]
