# Generated by Django 5.1.1 on 2024-09-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cbtbooktype',
            old_name='PR_IMPRINT_ID',
            new_name='PR_BOOK_TYPE_ID',
        ),
    ]
