# Generated by Django 5.1.1 on 2024-09-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteApp', '0002_rename_pr_imprint_id_cbtbooktype_pr_book_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbtseries',
            name='PR_BOARD_NAME',
        ),
        migrations.RemoveField(
            model_name='cbtseries',
            name='PR_CLASS_NAME',
        ),
    ]
