# Generated by Django 5.1.1 on 2024-09-22 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteApp', '0003_remove_cbtseries_pr_board_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtseries',
            name='PR_BOARD_NAME',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='websiteApp.cbtboard'),
        ),
        migrations.AddField(
            model_name='cbtseries',
            name='PR_CLASS_NAME',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='websiteApp.cbtclasses'),
        ),
    ]
