# Generated by Django 5.1.1 on 2024-09-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteApp', '0004_cbtseries_pr_board_name_cbtseries_pr_class_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cbtseries',
            old_name='PR_BOARD_NAME',
            new_name='PR_BOARD',
        ),
        migrations.RenameField(
            model_name='cbtseries',
            old_name='PR_CLASS_NAME',
            new_name='PR_CLASS',
        ),
    ]
