# Generated by Django 5.1.1 on 2024-09-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteApp', '0005_rename_pr_board_name_cbtseries_pr_board_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cbtexceldata',
            old_name='PR_EXCEL_DATA_ID',
            new_name='PR_BOOK_ID',
        ),
    ]
