# Generated by Django 5.1.1 on 2024-09-22 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteApp', '0006_rename_pr_excel_data_id_cbtexceldata_pr_book_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CbtExcelData',
            new_name='CbtBookData',
        ),
        migrations.AlterModelTable(
            name='cbtbookdata',
            table='cbt_book_data',
        ),
    ]
