# Generated by Django 5.1.1 on 2024-09-24 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteApp', '0007_rename_cbtexceldata_cbtbookdata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbtseries',
            name='PR_CLASS',
        ),
        migrations.CreateModel(
            name='CbtSeriesClass',
            fields=[
                ('PR_SERIES_CLASS_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
                ('PR_CLASS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteApp.cbtclasses')),
                ('PR_SERIES', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteApp.cbtseries')),
            ],
            options={
                'db_table': 'cbt_series_class',
                'unique_together': {('PR_CLASS', 'PR_SERIES')},
            },
        ),
        migrations.AddField(
            model_name='cbtseries',
            name='PR_CLASSES',
            field=models.ManyToManyField(related_name='series', through='websiteApp.CbtSeriesClass', to='websiteApp.cbtclasses'),
        ),
    ]
