# Generated by Django 5.1.1 on 2024-09-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteApp', '0008_remove_cbtseries_pr_class_cbtseriesclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbtbookdata',
            name='PR_AUTHOR',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cbtbookdata',
            name='PR_EDITION',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cbtbookdata',
            name='PR_IMPRINT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CbtAuthor',
        ),
        migrations.DeleteModel(
            name='CbtEdition',
        ),
        migrations.DeleteModel(
            name='CbtImprint',
        ),
    ]
