# Generated by Django 5.1.1 on 2024-09-24 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteApp', '0009_alter_cbtbookdata_pr_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbtseriesclass',
            name='PR_CREATED_AT',
        ),
        migrations.RemoveField(
            model_name='cbtseriesclass',
            name='PR_MODIFIED_AT',
        ),
        migrations.AddField(
            model_name='cbtbookdata',
            name='PR_BOARD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='websiteApp.cbtboard'),
        ),
        migrations.AddField(
            model_name='cbtbookdata',
            name='PR_CLASS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='websiteApp.cbtclasses'),
        ),
    ]
