# Generated by Django 5.1.1 on 2024-09-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteApp', '0010_remove_cbtseriesclass_pr_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cbtboard',
            old_name='PR_BOARD_NAME',
            new_name='PR_NAME',
        ),
        migrations.RenameField(
            model_name='cbtbooktype',
            old_name='PR_BOOK_NAME',
            new_name='PR_NAME',
        ),
        migrations.RenameField(
            model_name='cbtclasses',
            old_name='PR_CLASS_NAME',
            new_name='PR_NAME',
        ),
        migrations.RenameField(
            model_name='cbtseries',
            old_name='PR_SERIES_NAME',
            new_name='PR_NAME',
        ),
    ]
