# Generated by Django 5.1.1 on 2024-09-24 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteApp', '0011_rename_pr_board_name_cbtboard_pr_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbtbookdata',
            name='PR_BOOK_TYPE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='websiteApp.cbtbooktype'),
        ),
    ]
